<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CvCheck.Application\CvCheck.Application.csproj" />
    <ProjectReference Include="..\CvCheck.Infrastructure\CvCheck.Infrastructure.csproj" />
  </ItemGroup>

</Project>
